### ISSUE TITLE
Adding 'ref' attribute to component in router-view breaks beforeRouteEnter next( vm => {} )

### ISSUE THREAD

**Issue by AgileInteractive** [vuejs/vue-router-next#461] opened 2020-09-08 11:00 UTC
### Version
4.0.0-beta.9

### Reproduction link
[https://jsfiddle.net/1e9mqocg/1/](https://jsfiddle.net/1e9mqocg/1/)

### Steps to reproduce
Add router-view with transition

    <router-view v-slot="{ Component }">
      <transition v-on:enter="enterTransition">
        <component :is="Component" ref="myRouteComponent"/>
      </transition>
    </router-view>

Add beforeRouteEnter guard to child view

    beforeRouteEnter(to, from, next) {
        console.log('* beforeRouteEnter');
        next((vm) => { vm.setData(); } );
    },
  
    methods: {
        setData() {
            console.log('*** "Set data" from beforeRouteEnter here');
        }
    }

### What is expected?
setData() to be called when clicking "Home" (inspect console.log)

### What is actually happening?
setData is never called

---
Just deleting the 'ref' attribute makes it work again, but the ref attribute is very useful.

**Comment by posva** [comment] 2020-09-08 13:16
I think this one is a bug on vue. I will try to create a repro in the following days. The problem is we use our own `ref` to retrieve the component instance but it gets overriden by the user's.
If you want to try to reproduce it in Vue. The relevant code is in RouterView

```ts
setup(props, { slots }) {
return () => {
      const component = h(
        ViewComponent,
        {
          ref: viewRef, // a ref()
        }
      )

  return slots.default({ Component: component })
  }
}
```

**Comment by posva** [comment] 2020-09-09 10:22
Opened https://github.com/vuejs/vue-next/issues/2078

**Comment by posva** [comment] 2020-09-14 19:44
Fixed in vue-next

**Closed** 2020-09-14 19:44 UTC
Labels: bug, external

**Comment by marina-mosti** [comment] 2021-05-18 08:23
Hey @posva when this got fixed did the ability to target a `ref` inside the `router-view` slot get removed?
The following example with vue 3.1 and router 4 shows no ref whatsoever on the $refs object 🤔 

```
<router-view
    :key="$route.name"
    v-slot="{ Component }"
  >
    <component
      :is="Component"
    ref="routerView"
    />
  </router-view>
  ```

**Comment by posva** [comment] 2021-05-18 10:22
I don't know, the reproductions seem to work. A proper bug report would help
