### ISSUE TITLE
Component in RouterView doesn't run watch callback when wached ref updated from `onMounted`

### ISSUE THREAD

**Issue by JakubValtar** [vuejs/vue-router-next#754] opened 2021-02-03 20:37 UTC
### Version
4.0.3

### Reproduction link
[https://codepen.io/jakubvaltar/pen/gOLavPd?editors=1010](https://codepen.io/jakubvaltar/pen/gOLavPd?editors=1010)

### Steps to reproduce
1. Create a component
2. In `setup()`, create a `ref`
3. Use `watch()` to register a callback when the `ref` value changes
4. Change the `ref` value in `onMounted()`
5. Display the component within `RouterView`

### What is expected?
The watch callback runs.

### What is actually happening?
The watch callback does not run.

---
- When the `ref` is updated from `onBeforeMount()`, the callback runs.
- When running the component outside of `RouterView`, the callback runs.
- It seems that it does not run only when the `ref` is updated from `onMounted()` and the component is within `RouterView`.

**Comment by posva** [comment] 2021-02-04 21:14
Duplicate of https://github.com/vuejs/vue-next/issues/2730

**Comment by posva** [comment] 2021-02-04 21:15
Fixed by https://github.com/vuejs/vue-next/pull/2732

**Closed by posva** 2021-02-04 21:14 UTC

**Comment by JakubValtar** [comment] 2021-02-04 21:19
Ah, missed that one. Thanks!
