### ISSUE TITLE
Document params must be strings, numbers, or arrays of these (for repeated params) in programmatic navigation

### ISSUE THREAD

**Issue by laurikihva** [vuejs/vue-router-next#873] opened 2021-04-09 13:32 UTC
### Version
4.0.6

### Reproduction link
[https://codesandbox.io/s/dawn-pine-4yc98](https://codesandbox.io/s/dawn-pine-4yc98)

### Steps to reproduce
1. Press button on `Home` page which routes to `About` page with undefined `id` param.
2. Undefined `id` param is included in the URL & passed to `About` page as `string`

### What is expected?
Undefined params are not passed to URL & on the redirected page this param value should also be undefined

### What is actually happening?
Undefined is passed to the URL & is usable on the destination page as a string

---
Also happens if `id` is passed as `null`.<br>
Doesn't matter if param is optional or not:<br>
* `path: "about/:id"`
* `path: "about/:id?`

**Comment by posva** [comment] 2021-04-09 14:35
Duplicate of https://github.com/vuejs/vue-router-next/issues/855

**Comment by posva** [comment] 2021-04-09 14:35
Since this came up multiple times, I think we should say in the documentation that params must be strings

**Closed** 2021-06-14 14:06 UTC
Labels: docs
