### ISSUE TITLE
Is there any API to show the route is off?

### ISSUE THREAD

**Issue by LoveofRedMoon** [vuejs/vue-router-next#917] opened 2021-05-02 13:58 UTC
### What problem does this feature solve?
http://jsfiddle.net/b7f4dpkg/10
1. click 'foo'
2. click 'back'
you will see how computed value `testParam` changes by `watch`

when go to foo, testParam.value === 'queryParam'
when go back to the first page, testParam.value === null

I know why this value becomes null --- it shows the next route query value.
But this is not in common sense.
Usually, the query value use in this view page only for current scene.

For example. the edit page will show `edit` when query.id !== null, will show `create` when query.id === null
This scene will turn this page to `create` when leave this page

### What does the proposed API look like?
Should not load new query value when the previous view haven't be deactivated (instance.isDeactivated)

**Comment by posva** [comment] 2021-05-02 15:43
Duplicate of https://github.com/vuejs/vue-next/issues/2291

**Closed by posva** 2021-05-02 15:43 UTC
