### ISSUE TITLE
Suspense with <router-view> #fallback not working

### ISSUE THREAD

**Issue by iosamuel** [vuejs/vue-router-next#788] opened 2021-02-23 18:13 UTC
### Version
4.0.4

### Reproduction link
[https://jsfiddle.net/4asozkj3/](https://jsfiddle.net/4asozkj3/)

### Steps to reproduce
Go to the `Foo` route and you will see it does wait for the route to finish the promise, but it doesn't show the fallback.

Note that I tried two syntaxes, one with router-view v-slot (Component) prop and the other one with the simpler form of Suspense using router-view inside the Suspense #default slot, and neither of these works

Syntax form 1:
```
<Suspense>
  <template #default>
    <router-view />
  </template>
  <template #fallback>
    <h3>Loading...</h3>
  </template>
</Suspense>
```

Syntax form 2:
```
<router-view v-slot="{ Component }">
  <Suspense>
    <Suspense>
      <template #default>
        <component :is="Component" />
      </template>
      <template #fallback>
        <h3>Loading...</h3>
      </template>
    </Suspense>
  </Suspense>
</router-view>
```

### What is expected?
When using Suspense with an async component (even router-view as a wrapper) you should see the #fallback while the component is getting resolved

### What is actually happening?
No #fallback is showing while component loads

---
Suspense works well when using a normal import of a Component and using it directly in the template but not while using router-view

Maybe something changed that I'm not aware of, but couldn't find anything yet. Thanks in advance!

**Comment by posva** [comment] 2021-02-23 18:26
Duplicate of https://github.com/vuejs/vue-router-next/issues/560

**Closed by posva** 2021-02-23 18:26 UTC
