### ISSUE TITLE
Won't work with Suspense

### ISSUE THREAD

**Issue by yaquawa** [vuejs/vue-router-next#584] opened 2020-11-10 15:12 UTC
### Version
4.0.0-rc.2

### Reproduction link
[https://codesandbox.io/s/modest-butterfly-ih1jr?file=/src/App.vue](https://codesandbox.io/s/modest-butterfly-ih1jr?file=/src/App.vue)

### Steps to reproduce
This won't work
```html
<Suspense>
    <template #default>
        <router-view />
    </template>
    <template #fallback>
        <span>I'm a loading screen, I'm waiting the view to be ready!</span>
    </template>
</Suspense>
```

**Comment by posva** [comment] 2020-11-10 16:24
Looks like a regression in Vue, this used to work

**Comment by posva** [comment] 2020-11-10 16:26
Duplicate of https://github.com/vuejs/vue-next/issues/2215

**Closed by posva** 2020-11-10 16:26 UTC

**Comment by jods4** [comment] 2020-11-10 16:27
Apologies for posting vuejs/vue-router-next#3369 in the wrong repo.

It's a regression by design, it was part of vuejs/vue-next#2099.
Since then Suspense only goes back to pending state if its direct child is changed to an async setup.
Deeper changes, notably inside `<RouterView>` are silently ignored.

This is a very unfortunate change, and I'd gladly take any guidance from @posva regarding how to load routes that are async setup.

`beforeEnterRouter` is much, much less convenient to load data in a `setup()` world than it is in the Options API.

**Comment by jods4** [comment] 2020-11-10 16:31
@posva I'm not 100% confident closing as a duplicate is the right call.
It is the same issue, but vuejs/vue-next#2215 has not been acknowledged as a bug that will be fixed, as it was a by-design change.
If vuejs/vue-next#2215 doesn't lead to a reversal of the changes, this issue should be kept open to find an alternative solution.
The breakage impacting the router is quite bad but that issue wasn't fixed in 2 months, so not sure what to expect.

Suspense is experimental but there is no signal from the team whether this will change or not.

**Comment by yaquawa** [comment] 2020-11-10 17:05
@jods4 Thanks.
> beforeEnterRouter is much, much less convenient to load data in a setup() world than it is in the Options API.

Yes, no doubt about that.

@posva 
will vue-router use an inner Suspense to wrap the given component in the feature version?

**Comment by yaquawa** [comment] 2021-01-18 11:16
Hi @posva https://github.com/vuejs/vue-next/issues/2215 has been fixed. But still I can confirm the issue with vue-router.
This is really inconvenient that a component can not use `async setup()`. I alway have to go to the old school way to do a `loading now` indicator manually with every each component. Hope this will be fixed.

**Comment by posva** [comment] 2021-01-18 14:00
Proper integration with Suspense will likely go through an RFC to support the loading screen. It might also need changes in Vue core. That being said, the initial issue was fixed: the code displays the view instead of erroring.

**Comment by jods4** [comment] 2021-01-18 15:31
@posva I haven't had time to try the fixes in my project but I intend to and I'm a bit confused by the last 2 comments.
What works now and what doesn't?
Isn't "Loading screen" just a matter of using `Suspense` loading slot? Do you have something more integrated with Router in mind?

@jods4 Yes, I have a workaround in place in my project but it's not nice.
Basically I created a functional wrapper that simply puts a `<Suspense>` (with loading template, etc.) around any other component.
And for now, every single page in my app looks like this:
```html
<template>
  Template as usual
</template>
<script>
// Notice I'm not exporting yet
const page = defineComponent({
  // Your component as usual
  async setup() { }
});

// This wraps the component in its own Suspense
export default suspenseWrapper(page);
</script>
```

And so, instead of having a `<Suspense>` around my router, every async page has its own `<Suspense>` around itself.
Of course this only works with async pages, not their async contents.
Before the fix you need one `Suspense` _directly_ around any async component.

**Comment by yaquawa** [comment] 2021-01-21 04:27
@jods4 Thanks for the sample code!!
Could you show me the code for your `suspenseWrapper` ?!

**Comment by jods4** [comment] 2021-01-21 08:18
@yaquawa You are right, my code is actually slightly different because you can't do the wrapping like that in the SFC.
I do the wrapping in the route table:
```ts
export default <RouteRecordRaw[]>[
  { path: "/", component: suspenseHack(Home) },
  // etc.
]
```
Conveniently, this is the only file where `suspenseHack` is imported and used.

The full code for the wrapper is here:
```ts
// HACK: this is a dirty workaround for Suspense not working
//       with components that are not its direct children
//       since https://github.com/vuejs/vue-next/pull/2099
//       See also this discussion:
//       https://github.com/vuejs/vue-next/issues/2215
//       Could be better supported with direct Router support:
//       https://github.com/vuejs/vue-router-next/issues/584

import { Component, FunctionalComponent, h, Suspense } from "vue";

export function suspenseHack(component: Component) {
  const wrapper: FunctionalComponent = () =>
    h(Suspense, null, {
      default() {
        return h(component);
      },
      fallback() {
        return h("app-loading");  // <-- REPLACE THIS WITH YOUR OWN FALLBACK
      },
    });
  wrapper.displayName = "SuspenseHack";
  return wrapper;
}
```

Please note that I haven't tested this code with versions of Vue that contain the fix for this issue.

**Comment by yaquawa** [comment] 2021-01-25 09:43
@jods4 Thanks for the sample code!! Fantastic!

**Comment by paprika135** [comment] 2024-05-13 06:53
> @jods4 Thanks for the sample code!! Fantastic!

 为什么我试这段代码 完全不起作用？

**Comment by paprika135** [comment] 2024-05-13 07:16
> @yaquawa You are right, my code is actually slightly different because you can't do the wrapping like that in the SFC. I do the wrapping in the route table:
> 
> ```ts
> export default <RouteRecordRaw[]>[
>   { path: "/", component: suspenseHack(Home) },
>   // etc.
> ]
> ```
> 
> Conveniently, this is the only file where `suspenseHack` is imported and used.
> 
> The full code for the wrapper is here:
> 
> ```ts
> // HACK: this is a dirty workaround for Suspense not working
> //       with components that are not its direct children
> //       since https://github.com/vuejs/vue-next/pull/2099
> //       See also this discussion:
> //       https://github.com/vuejs/vue-next/issues/2215
> //       Could be better supported with direct Router support:
> //       https://github.com/vuejs/vue-router-next/issues/584
> 
> import { Component, FunctionalComponent, h, Suspense } from "vue";
> 
> export function suspenseHack(component: Component) {
>   const wrapper: FunctionalComponent = () =>
>     h(Suspense, null, {
>       default() {
>         return h(component);
>       },
>       fallback() {
>         return h("app-loading");  // <-- REPLACE THIS WITH YOUR OWN FALLBACK
>       },
>     });
>   wrapper.displayName = "SuspenseHack";
>   return wrapper;
> }
> ```
> 
> Please note that I haven't tested this code with versions of Vue that contain the fix for this issue.

I encountered two problems:
1. After using your method, do I still need to wrap the "router-view" label with a "suspense" label?------I guess "no"
2.When I use suspenseHack function in the RouteRecordRaw object's component props, Vue cannot recognize this component,so it's display nothing.
3. "wrapper. displayName" is equivalent to hanging a displayName property on a component instance with a value of "SuspendeHack", but why do this?

**Comment by jods4** [comment] 2024-05-13 08:27
@paprika135 This issue has been closed, the hack above has not been required for many Vue releases now.
The simple markup posted by OP should work. If it doesn't work in your project, you should make a repro and open a new issue.
