### ISSUE TITLE
Doesn't work in Edge browser

### ISSUE THREAD

**Issue by stbit** [vuejs/vue-router-next#317] opened 2020-06-21 00:56 UTC
### Version
4.0.0-alpha.13

### Reproduction link
[https://github.com/stbit/vue-route-test](https://github.com/stbit/vue-route-test)

### Steps to reproduce
Open in Edge(my Microsoft Edge 44.18362.449.0). The page is not displayed. In console "0: Expected '('". Swears on catch without parameter https://github.com/vuejs/vue-router-next/blob/master/src/scrollBehavior.ts#L120. If you add a parameter, then everything is displayed normally (...catch(e)...)

### What is expected?
Page display

### What is actually happening?
Page not displaying

**Comment by posva** [comment] 2020-06-21 11:48
Duplicate of https://github.com/vuejs/vue-router-next/issues/304

**Closed by posva** 2020-06-21 11:48 UTC
