### ISSUE TITLE
popstate and beforeunload listener was not removed when vue unmount

### ISSUE THREAD

**Issue by wannasky** [vuejs/vue-router-next#452] opened 2020-09-06 10:55 UTC
### Version
4.0.0-beta.9

### What is expected?
remove popstate and beforeunload listener when vue unmount

### What is actually happening?
 popstate and beforeunload listeners were not removed when vue was unmount

---
When I modified Vue with single-spa, I found that I could not jump out of Vue application

**Comment by wannasky** [comment] 2020-09-06 11:05
And I solve this problem by:

router.ts
```typescript
export const routerHistory = createWebHashHistory((window as any).__SINGLE__SPA ? '/vue' : process.env.BASE_URL);

const router = createRouter({
  history: routerHistory,
  routes
})

export default router
```

when unmount add:
```typescript
routerHistory.destroy();
```

**Comment by posva** [comment] 2020-09-06 17:15
The router removes its own listener on the history instance but the `popstate` event is kept for the history. So guards are not executed.

Why do you need the event to be removed?

**Comment by wannasky** [comment] 2020-09-07 02:00
[single-spa pushState](https://github.com/single-spa/single-spa/blob/master/src/navigation/navigation-events.js#L161)  method is overridden by creating a PopStateEvent，so the popstate event is triggered. 

so, should the `popostate` event be cleared when Vue is unmounted?

**Comment by posva** [comment] 2020-09-07 07:27
I don't think it needs to be removed (or avoided) as long as it's not harmful since as long as there is no mounted app, the router isn't listening to history navigations.

Have you found any problem you can provide as a boiled down reproduction?

**Comment by posva** [comment] 2020-09-11 09:09
Closing as this doesn't seem to be a problem but feel free to post new messages and I will reopen the issue

**Closed by posva** 2020-09-11 09:09 UTC
Labels: discussion
