### ISSUE TITLE
Redirect in nested children is not honoured when link to a name location

### ISSUE THREAD

**Issue by AlexandreBonaventure** [vuejs/vue-router-next#310] opened 2020-06-15 21:49 UTC
### Version
4.0.0-alpha.12

### Reproduction link
[https://jsfiddle.net/qp1tu5ds/1/](https://jsfiddle.net/qp1tu5ds/1/)

### What is expected?
 Same behaviour between name-based location link vs path-based location link

### What is actually happening?
When using name-based location children redirect route record is not hit.

**Comment by posva** [comment] 2020-06-15 22:40
Duplicate of #309

**Closed by posva** 2020-06-15 22:40 UTC
