### ISSUE TITLE
VueRouter ios  safari10.2 Error

### ISSUE THREAD

**Issue by leafront** [vuejs/vue-router-next#882] opened 2021-04-14 10:40 UTC
### Version
4.0.4

### Reproduction link
[https://h5-new-test.haoyishu.org](https://h5-new-test.haoyishu.org)

### Steps to reproduce
ios safari 10.2 browser Cannot declare a let variable twice: 'e'.

### What is expected?
Good

### What is actually happening?
Good

**Comment by posva** [comment] 2021-04-14 11:16
Please read https://new-issue.vuejs.org/?repo=vuejs/vue-router-next#why-repro and open a new issue if you manage to reproduce it.

You should check if building vue-router with the option added at https://github.com/vuejs/vue-router-next/pull/826 solves the issue for you. It didn't seem to change the output of the bundler version so the PR never got merged but it seems to be the same problem.

If you are using Vite, you should include that option in https://vitejs.dev/config/#build-terseroptions but the problem is unrelated to Vue Router

**Closed by posva** 2021-04-14 11:16 UTC
