### ISSUE TITLE
The routing address can fuzzy match the to attribute of multiple router-link components.  but router-link-active does not add

### ISSUE THREAD

**Issue by zhousg** [vuejs/vue-router-next#832] opened 2021-03-17 09:15 UTC
### Version
4.0.5

### Reproduction link
[https://jsbin.com/qawexar/edit?html,console,output](https://jsbin.com/qawexar/edit?html,console,output)

### Steps to reproduce
    <router-link to="/member">个人中心</router-link>
    <router-link to="/member/order">我的订单</router-link>

if address is  /member/order/123  

### What is expected?
The second route has the router-link-active class name

### What is actually happening?
But no

**Comment by posva** [comment] 2021-03-17 09:22
Duplicate of #752

**Closed by posva** 2021-03-17 09:22 UTC

**Comment by zhousg** [comment] 2021-03-17 13:05
component: { render: () => h(<RouterView/>) },
            children: [
              { path: '', component: MemberOrder },
              { path: ':id', component: MemberOrderDetail }
            ]
