### ISSUE TITLE
Support for Vite generated template

### ISSUE THREAD

**Issue by nicoabie** [vuejs/vue-router-next#858] opened 2021-04-01 22:40 UTC
### What problem does this feature solve?
Currently the instructions to make vue-router@next with vue@next do not take into consideration the scenario where the vue application was generated by vite and has a module bundler such as rollup. The instructions just demonstrate that it is possible make it work with an index file that points to CDNs and has a script tag.

Trying to follow those instructions with a generated vue template and making the necessary teaks such as not pointing to the CDNs because there is already a main file that resolves those imports results in an error.

[Vue warn]: Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js"

The way I managed to solve it was:
```js
import { createApp } from 'vue/dist/vue.esm-bundler.js'
import { createRouter, createWebHashHistory } from 'vue-router'
```
As I didn't like that reference there I tried tweaking vite.config.js
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import alias from '@rollup/plugin-alias';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue()],
  build: {
    rollupOptions: {
      plugins: [
        alias({
          entries: [{ find: 'vue', replacement: '/node_modules/vue/dist/vue.esm-bundler.js' }]
        })
      ]
    }
  }
})
```
But it unfortunately didn't work.

It would be really nice if vue-router@next has an official documentation describing how to make the router work in that scenario since in these days vite is gaining a lot of traction.

Thanks in advance,
If needed I can provide a repository showing the issue but it is very easy to replicate.

### What does the proposed API look like?
There is no change in the api itself, just support for vite module bundler.

**Comment by posva** [comment] 2021-04-02 07:56
Duplicate of #829

**Comment by posva** [comment] 2021-04-02 07:57
You don't need to configure anything to make vue router work with Vite

**Closed by posva** 2021-04-02 07:57 UTC

**Comment by nicoabie** [comment] 2021-04-02 14:52
@posva If that is the case why I can't make it work with this line that would be the correct:
`import { createApp } from 'vue'`
And I have to hack it pointing to a specific bundler?
`import { createApp } from 'vue/dist/vue.esm-bundler.js'`

I was getting an error:
[Vue warn]: Component provided template option but runtime compilation is not supported in this build of Vue. Configure your bundler to alias "vue" to "vue/dist/vue.esm-bundler.js"

Could you point me to the right direction?

**Comment by sparrowhawk-ea** [comment] 2021-04-21 10:38
This worked for me in vite.config.ts
`
export default defineConfig({
  define: {
    'process.env': {}
  },
  plugins: [vue()],
  resolve: {
    alias: {
      'vue': 'vue/dist/vue.esm-bundler.js'
    }
  }
})
`

**Comment by nicoabie** [comment] 2021-04-21 15:26
@sparrowhawk-ea thar makes a lot of sense, thanks a lot!!!

**Comment by yuber83** [comment] 2021-07-17 15:28
@sparrowhawk-ea  thanks, 
you save me a lot of time.

**Comment by grefl** [comment] 2022-06-27 17:33
Hmmm. I had the same problem. Except @sparrowhawk-ea's solution fixed my issue. 

Considering all the upvotes for @sparrowhawk-ea post I think it worth a mention from the maintainers why this is still a common thing for people to come across. @posva
