### ISSUE TITLE
empty route-view cause transition failed

### ISSUE THREAD

**Issue by yoyoys** [vuejs/vue-router-next#386] opened 2020-07-24 12:59 UTC
### Version
4.0.0-beta.3

### Reproduction link
[https://github.com/yoyoys/vue-router-next-transition-bug](https://github.com/yoyoys/vue-router-next-transition-bug)

### Steps to reproduce
1. switch to Empty test route
2. switch back to any route

here is gif version

2.x
![2020-07-24 19 37 08](https://user-images.githubusercontent.com/22124891/88387618-6beb2980-cde5-11ea-8315-7a09b7efc237.gif)
3.x
![2020-07-24 19 37 52](https://user-images.githubusercontent.com/22124891/88387628-71e10a80-cde5-11ea-984c-03bcebc59ac3.gif)

### What is expected?
the transition should be applied.

### What is actually happening?
nothing happened, but the transition will apply on other component or non-empty route

---
This bug made nest route transition failed.

**Comment by posva** [comment] 2020-07-24 13:13
Duplicate of https://github.com/vuejs/vue-router-next/issues/385

**Comment by posva** [comment] 2020-07-24 13:13
the fix will be included in the next release

**Closed by posva** 2020-07-24 13:13 UTC

**Comment by yoyoys** [comment] 2020-07-24 13:16
My mistake, I paste wrong issue.
