### ISSUE TITLE
VueRouter 4.0.8 esm-browser build broken

### ISSUE THREAD

**Issue by sfaut** [vuejs/vue-router-next#961] opened 2021-05-23 22:12 UTC
### Version
4.0.8

### Reproduction link
[https://codepen.io/JCH77/pen/ExWmjNy](https://codepen.io/JCH77/pen/ExWmjNy)

### Steps to reproduce
Use esm-browser builds 
Import Vue 3.0.11 => OK 
Import VueRouter 4.0.8 => The following error occurs : 
*Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".*

### What is expected?
VueRouter esm-browser build import success

### What is actually happening?
VueRouter esm-browser build import fail

**Comment by posva** [comment] 2021-05-26 07:48
Please search existing issues before opening one.
Duplicate of #694

**Closed by posva** 2021-05-26 07:48 UTC
